export const LIST_READ = 'LIST_READ'
export const LIST_CREATE = 'LIST_CREATE'
export const LIST_UPDATE = 'LIST_UPDATE'
export const LIST_DELETE = 'LIST_DELETE'
export const LOADING = 'LOADING'
export const ERROR = 'ERROR'